web:
  build: .
  command: /mnt/src/start_service.sh
  links:
   - db
  ports:
   - "8000:8000"
  volumes:
   - src:/mnt/src
  environment:
    RAILS_ENV: development
    GIT_BRANCH: develop
db:
  image: mongo
  ports:
   - "27017:27017"
